[font]
size = 20.0

[colors.primary]
background = "#101010"
foreground = "#eeeeee"

[colors.selection]
text = "#dddddd"
background = "#282828"

[colors.cursor]
text = "#101010"
cursor = "#cccccc"

[colors.normal]
black   = "#2a2a2a"
red     = "#ba0959"
green   = "#1bfd9c"
yellow  = "#b4b4b4"
blue    = "#7a7a7a"
magenta = "#708090"
cyan    = "#66b2b2"
white   = "#f1f1f1"

[colors.bright]
black   = "#4a4a4a"
red     = "#fd1b7c"
green   = "#66ffad"
yellow  = "#dddddd"
blue    = "#aaaaaa"
magenta = "#879aad"
cyan    = "#49c4c4"
white   = "#ffffff"
