#!/usr/bin/env bash
dir=$(find ~/ -maxdepth 2 -print | grep -E "Learn|Projects" | fzf)


[ -z "$dir" ] && exit

session="${dir//./_}"

if ! tmux has-session -t "$session" 2>/dev/null; then
  cd "$dir"
  tmux new-session -d -s "$session" -c "$dir"
  tmux send-keys -t "$session":1 'nvim .' C-m
  tmux select-window -t :1
fi

if [ -n "$TMUX" ]; then
  tmux switch-client -t "$session"
else
  tmux attach -t "$session"
fi

